M48
; DRILL file {KiCad (6.0.0-rc1-415-g653c7b78d7)} date Thu Dec 23 14:24:12 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-12-23T14:24:12-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-rc1-415-g653c7b78d7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X147.005Y-52.495
X147.005Y-125.995
T0
M30
