M48
; DRILL file {KiCad (6.0.0-rc1-415-g653c7b78d7)} date Tue Dec 14 13:19:58 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-12-14T13:19:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-rc1-415-g653c7b78d7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X132.725Y-54.56
X132.725Y-97.06
T0
M30
